model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 32
    n_embed: 4096
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 512
      in_channels: 1
      out_ch: 1
      ch: 64
      ch_mult:
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 1
        disc_start: 1
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 0
    wrap: true
    train:
      target: ldm.data.dental_stage1.DentalTrain
      params:
        conditioning:
        - pre
        data_path: /workspace/jjh/25.CephGeneration/split_data/whole
        size: 512
        crop_size: 512
        image: false
        threshold: 0.5

    validation:
      target: ldm.data.dental_stage1.DentalValidation
      params:
        conditioning:
        - pre
        data_path: /workspace/jjh/25.CephGeneration/split_data/whole
        size: 512
        crop_size: 512
        image: false
        threshold: 0.5
