model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 16
    n_embed: 8192
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 8
      resolution: 1024
      in_channels: 1
      out_ch: 1
      ch: 64
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      - 8
      num_res_blocks: 2
      attn_resolutions:
      - 32
      - 16
      - 8
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 1
        disc_start: 50001
        disc_weight: 0.75
        disc_num_layers: 3
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    wrap: true
    train:
      target: ldm.data.dental_registration.DentalTrain
      params:
        conditioning:
        - pre
        data_path: /workspace/jjh/25.CephGeneration/split_data/train
        size: 1024
        crop_size: 1024
        image: false
        threshold: 0.5

    validation:
      target: ldm.data.dental_registration.DentalValidation
      params:
        conditioning:
        - pre
        data_path: /workspace/jjh/25.CephGeneration/split_data/test
        size: 1024
        crop_size: 1024
        image: false
        threshold: 0.5
